In [1]:
import yaml

In [3]:
with open('src/digits.yaml', 'r') as digits:
    sym_map = yaml.load(digits)
print sym_map

{'seven': [1, 0, 1, 0, 0, 1, 0], 'six': [1, 1, 0, 1, 1, 1, 1], 'three': [1, 0, 1, 1, 0, 1, 1], 'two': [1, 0, 1, 1, 1, 0, 1], 'four': [0, 1, 1, 1, 0, 1, 0], 'zero': [1, 1, 1, 0, 1, 1, 1], 'nine': [1, 1, 1, 1, 0, 1, 1], 'five': [1, 1, 0, 1, 0, 1, 1], 'one': [0, 0, 1, 0, 0, 1, 0], 'eight': [1, 1, 1, 1, 1, 1, 1]}


In [4]:
type(sym_map)

dict

In [5]:
for key, value in sym_map.iteritems():
    print key, value

seven [1, 0, 1, 0, 0, 1, 0]
six [1, 1, 0, 1, 1, 1, 1]
three [1, 0, 1, 1, 0, 1, 1]
two [1, 0, 1, 1, 1, 0, 1]
four [0, 1, 1, 1, 0, 1, 0]
zero [1, 1, 1, 0, 1, 1, 1]
nine [1, 1, 1, 1, 0, 1, 1]
five [1, 1, 0, 1, 0, 1, 1]
one [0, 0, 1, 0, 0, 1, 0]
eight [1, 1, 1, 1, 1, 1, 1]


In [6]:
a = [1, 2, 3]

In [7]:
a.insert(0, 4)

In [8]:
a

[4, 1, 2, 3]

In [9]:
import numpy as np
a = np.array([])

In [10]:
a

array([], dtype=float64)

In [11]:
np.append(a, np.zeros(3))

array([ 0.,  0.,  0.])

In [16]:
a = np.append(a, np.zeros(3, dtype=int))

In [17]:
a

array([ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.])

In [14]:
a =np.append(a, np.ones(3))

In [15]:
a

array([ 0.,  0.,  0.,  1.,  1.,  1.])

In [20]:
a = np.array([], dtype = int)

In [21]:
a

array([], dtype=int64)

In [22]:
a = np.append(a, np.zeros(3, dtype=int))

In [23]:
a

array([0, 0, 0])

In [24]:
import InputWorld

ImportError: No module named InputWorld

In [25]:
np.__version__

'1.9.2'

In [26]:
from larson import InputWorld

In [28]:
world = InputWorld.Digits(2, 'larson/digits.yaml')

In [29]:
world.sym_map

{'eight': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'five': array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1]),
 'four': array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0]),
 'nine': array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 'one': array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 'seven': array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 'six': array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]),
 'three': array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 'two': array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1]),
 'zero': array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1])}

In [30]:
sym_map = world.sym_map

In [31]:
import random

In [37]:
random.choice(sym_map.values())

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [33]:
dir(d)

NameError: name 'd' is not defined

In [45]:
random.random()* 0.1

0.09173312376564607

In [47]:
world.ran_input()

[]

In [49]:
world = InputWorld.Digits(2, 'norms/digits.yaml')

In [50]:
world.ran_input()

[]

In [51]:
world = InputWorld.Digits(2, 'norms/digits.yaml')

In [53]:
world.ran_input()

[]

In [54]:
world.ran_input

<bound method Digits.ran_input of <larson.InputWorld.Digits object at 0x108432790>>

In [55]:
from larson import InputWorld

In [56]:
world = InputWorld.Digits(2, 'norms/digits.yaml')

In [57]:
world.ran_input()

[]

In [58]:
world.sym_map.values()

[array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1]),
 array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])]

In [59]:
vec = random.choice(world.sym_map.values())

In [60]:
ran_input = []
for dim in vec:
    if dim == 0:
        ran_input.append(random.random() * 0.1)
    if dim == 1:
        ran_input.append(1 - random.random() * 0.1)

        
print ran_input

[0.9865202693570323, 0.9529077675143375, 0.9570623429924292, 0.9241590825313747, 0.006904366459821521, 0.08727315112063871, 0.9798494639518593, 0.916407241910316, 0.9594793576749865, 0.9398598078293776, 0.9976156762829789, 0.9727305075337376, 0.9716153794071628, 0.9905252827057193]


In [1]:
from larson import InputWorld
world = InputWorld.Digits(2, 'norms/digits.yaml')

In [3]:
world.ran_input()

[0.932994231994474,
 0.9774117475164816,
 0.923788268747098,
 0.9573072158546749,
 0.9752781750445463,
 0.9891691781338255,
 0.9193320561302276,
 0.9641281373704662,
 0.9932105261567011,
 0.9345052958265655,
 0.9038735915871826,
 0.9968413176774055,
 0.905963679290164,
 0.941486290279191]

In [1]:
import numpy as np

In [2]:
np.random.rand(3,3,7)

array([[[ 0.39838754,  0.21162336,  0.40829892,  0.43724667,  0.31429553,
          0.53109259,  0.21373086],
        [ 0.07676914,  0.7801672 ,  0.83147239,  0.13423226,  0.34951778,
          0.44325663,  0.6335547 ],
        [ 0.99847095,  0.45528328,  0.24171749,  0.35120474,  0.51847283,
          0.80608497,  0.56025275]],

       [[ 0.05084297,  0.45954723,  0.3985765 ,  0.92874812,  0.31548711,
          0.75727673,  0.86141704],
        [ 0.62712002,  0.38557862,  0.46576203,  0.99715364,  0.2207148 ,
          0.51761617,  0.70948349],
        [ 0.61346494,  0.79538207,  0.23502452,  0.72917986,  0.18227146,
          0.01028789,  0.88341062]],

       [[ 0.61943909,  0.0746108 ,  0.1635551 ,  0.95930946,  0.61804324,
          0.93363925,  0.2735165 ],
        [ 0.27643628,  0.52326782,  0.63949072,  0.2735442 ,  0.6500041 ,
          0.10698229,  0.87083143],
        [ 0.44773617,  0.30025135,  0.53644012,  0.76231601,  0.03578153,
          0.22700208,  0.40804485]]])