In [1]:
import yaml

In [3]:
with open('src/digits.yaml', 'r') as digits:
    sym_map = yaml.load(digits)
print sym_map

{'seven': [1, 0, 1, 0, 0, 1, 0], 'six': [1, 1, 0, 1, 1, 1, 1], 'three': [1, 0, 1, 1, 0, 1, 1], 'two': [1, 0, 1, 1, 1, 0, 1], 'four': [0, 1, 1, 1, 0, 1, 0], 'zero': [1, 1, 1, 0, 1, 1, 1], 'nine': [1, 1, 1, 1, 0, 1, 1], 'five': [1, 1, 0, 1, 0, 1, 1], 'one': [0, 0, 1, 0, 0, 1, 0], 'eight': [1, 1, 1, 1, 1, 1, 1]}


In [4]:
type(sym_map)

dict

In [5]:
for key, value in sym_map.iteritems():
    print key, value

seven [1, 0, 1, 0, 0, 1, 0]
six [1, 1, 0, 1, 1, 1, 1]
three [1, 0, 1, 1, 0, 1, 1]
two [1, 0, 1, 1, 1, 0, 1]
four [0, 1, 1, 1, 0, 1, 0]
zero [1, 1, 1, 0, 1, 1, 1]
nine [1, 1, 1, 1, 0, 1, 1]
five [1, 1, 0, 1, 0, 1, 1]
one [0, 0, 1, 0, 0, 1, 0]
eight [1, 1, 1, 1, 1, 1, 1]


In [6]:
a = [1, 2, 3]

In [7]:
a.insert(0, 4)

In [8]:
a

[4, 1, 2, 3]

In [9]:
import numpy as np
a = np.array([])

In [10]:
a

array([], dtype=float64)

In [11]:
np.append(a, np.zeros(3))

array([ 0.,  0.,  0.])

In [16]:
a = np.append(a, np.zeros(3, dtype=int))

In [17]:
a

array([ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.])

In [14]:
a =np.append(a, np.ones(3))

In [15]:
a

array([ 0.,  0.,  0.,  1.,  1.,  1.])

In [20]:
a = np.array([], dtype = int)

In [21]:
a

array([], dtype=int64)

In [22]:
a = np.append(a, np.zeros(3, dtype=int))

In [23]:
a

array([0, 0, 0])

In [24]:
import InputWorld

ImportError: No module named InputWorld

In [25]:
np.__version__

'1.9.2'