In [1]:
import yaml

In [3]:
with open('src/digits.yaml', 'r') as digits:
    sym_map = yaml.load(digits)
print sym_map

{'seven': [1, 0, 1, 0, 0, 1, 0], 'six': [1, 1, 0, 1, 1, 1, 1], 'three': [1, 0, 1, 1, 0, 1, 1], 'two': [1, 0, 1, 1, 1, 0, 1], 'four': [0, 1, 1, 1, 0, 1, 0], 'zero': [1, 1, 1, 0, 1, 1, 1], 'nine': [1, 1, 1, 1, 0, 1, 1], 'five': [1, 1, 0, 1, 0, 1, 1], 'one': [0, 0, 1, 0, 0, 1, 0], 'eight': [1, 1, 1, 1, 1, 1, 1]}


In [4]:
type(sym_map)

dict

In [5]:
for key, value in sym_map.iteritems():
    print key, value

seven [1, 0, 1, 0, 0, 1, 0]
six [1, 1, 0, 1, 1, 1, 1]
three [1, 0, 1, 1, 0, 1, 1]
two [1, 0, 1, 1, 1, 0, 1]
four [0, 1, 1, 1, 0, 1, 0]
zero [1, 1, 1, 0, 1, 1, 1]
nine [1, 1, 1, 1, 0, 1, 1]
five [1, 1, 0, 1, 0, 1, 1]
one [0, 0, 1, 0, 0, 1, 0]
eight [1, 1, 1, 1, 1, 1, 1]


In [6]:
a = [1, 2, 3]

In [7]:
a.insert(0, 4)

In [8]:
a

[4, 1, 2, 3]

In [9]:
import numpy as np
a = np.array([])

In [10]:
a

array([], dtype=float64)

In [11]:
np.append(a, np.zeros(3))

array([ 0.,  0.,  0.])

In [16]:
a = np.append(a, np.zeros(3, dtype=int))

In [17]:
a

array([ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.])

In [14]:
a =np.append(a, np.ones(3))

In [15]:
a

array([ 0.,  0.,  0.,  1.,  1.,  1.])

In [20]:
a = np.array([], dtype = int)

In [21]:
a

array([], dtype=int64)

In [22]:
a = np.append(a, np.zeros(3, dtype=int))

In [23]:
a

array([0, 0, 0])

In [24]:
import InputWorld

ImportError: No module named InputWorld

In [25]:
np.__version__

'1.9.2'

In [26]:
from larson import InputWorld

In [28]:
world = InputWorld.Digits(2, 'larson/digits.yaml')

In [29]:
world.sym_map

{'eight': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'five': array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1]),
 'four': array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0]),
 'nine': array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 'one': array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 'seven': array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 'six': array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]),
 'three': array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 'two': array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1]),
 'zero': array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1])}

In [30]:
sym_map = world.sym_map

In [31]:
import random

In [37]:
random.choice(sym_map.values())

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [33]:
dir(d)

NameError: name 'd' is not defined

In [45]:
random.random()* 0.1

0.09173312376564607

In [47]:
world.ran_input()

[]

In [49]:
world = InputWorld.Digits(2, 'norms/digits.yaml')

In [50]:
world.ran_input()

[]

In [51]:
world = InputWorld.Digits(2, 'norms/digits.yaml')

In [53]:
world.ran_input()

[]

In [54]:
world.ran_input

<bound method Digits.ran_input of <larson.InputWorld.Digits object at 0x108432790>>

In [55]:
from larson import InputWorld

In [56]:
world = InputWorld.Digits(2, 'norms/digits.yaml')

In [57]:
world.ran_input()

[]

In [58]:
world.sym_map.values()

[array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1]),
 array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])]

In [59]:
vec = random.choice(world.sym_map.values())

In [60]:
ran_input = []
for dim in vec:
    if dim == 0:
        ran_input.append(random.random() * 0.1)
    if dim == 1:
        ran_input.append(1 - random.random() * 0.1)

        
print ran_input

[0.9865202693570323, 0.9529077675143375, 0.9570623429924292, 0.9241590825313747, 0.006904366459821521, 0.08727315112063871, 0.9798494639518593, 0.916407241910316, 0.9594793576749865, 0.9398598078293776, 0.9976156762829789, 0.9727305075337376, 0.9716153794071628, 0.9905252827057193]


In [1]:
from larson import InputWorld
world = InputWorld.Digits(2, 'norms/digits.yaml')

In [3]:
world.ran_input()

[0.932994231994474,
 0.9774117475164816,
 0.923788268747098,
 0.9573072158546749,
 0.9752781750445463,
 0.9891691781338255,
 0.9193320561302276,
 0.9641281373704662,
 0.9932105261567011,
 0.9345052958265655,
 0.9038735915871826,
 0.9968413176774055,
 0.905963679290164,
 0.941486290279191]

In [1]:
import numpy as np

In [3]:
a =np.random.rand(3,3,7)

In [4]:
a[1][1]

array([ 0.64433288,  0.91989794,  0.62050132,  0.38684323,  0.22454693,
        0.34489542,  0.53806576])

In [1]:
import numpy as np

In [9]:
a = np.zeros((3,3,7))
np.prod(a.shape[0:2])

9

In [12]:
for i in range(2):
    for j in range(i):
        print i,j

1 0


In [13]:
a = np.array([3,3,3])
b = np.array([2,2,2])
np.linalg.norm(a - b)

1.7320508075688772

In [14]:
a -b

array([1, 1, 1])

In [15]:
10 * np.ones((2,2))

array([[ 10.,  10.],
       [ 10.,  10.]])

In [16]:
a = {}
a[1] = 2
a[2] = 3

In [17]:
a

{1: 2, 2: 3}

In [18]:
for key in a.keys():
    print type(key)

<type 'int'>
<type 'int'>


In [19]:
np.ones(3)

array([ 1.,  1.,  1.])

In [31]:
a = np.array([[1,1],[3,4]])
a

array([[1, 1],
       [3, 4]])

In [21]:
np.argmin(a)

0

In [32]:
index = np.where(a == a.min())

In [33]:
index

(array([0, 0]), array([0, 1]))

In [30]:
type(index[0])

numpy.ndarray

In [34]:
a = {}
a[(0,0)] = 1
a[(0,1)] = 2
a

{(0, 0): 1, (0, 1): 2}

In [46]:
a = {}
a[0] = [1]
a[1] = [2]

In [47]:
a

{0: [1], 1: [2]}

In [48]:
a[0].extend(a[1])

In [49]:
a

{0: [1, 2], 1: [2]}

In [50]:
del a[1]

In [51]:
a

{0: [1, 2]}

In [52]:
a

{0: [1, 2]}

In [61]:
a ={}

In [62]:
a[2] = 1
a[1] = 2

In [66]:
type(a.values())

list

In [64]:
min(a)

1

In [67]:
a= {}
a[(0,0)] = 0
a[(1,1)] = 1
min(a, key=a.get)

(0, 0)

In [68]:
a = [3,2,1]
a.sort()

In [69]:
a

[1, 2, 3]

In [70]:
a = {}
a[(2,1)] = 0
a[(1,2)] = 1
a

{(1, 2): 1, (2, 1): 0}

In [71]:
for key in a.keys():
    print type(key)

<type 'tuple'>
<type 'tuple'>


In [73]:
b = tuple([1,2])

In [74]:
b

(1, 2)

In [75]:
type(b)

tuple

In [76]:
for key in a.keys():
    print type(key) == type(b)

True
True


In [77]:
min((0,1))

0

In [78]:
if 0 in (0,1):
    print 'HAHAHAAH'

HAHAHAAH


In [79]:
a = np.array([1,1])

In [80]:
a - 2

array([-1, -1])

In [81]:
a = np.array([[1,1], [2,2]])
a[:] - np.array([1,2])

array([[ 0, -1],
       [ 1,  0]])

In [82]:
a = np.array([[4,3],[2,1]])

In [83]:
a

array([[4, 3],
       [2, 1]])

In [85]:
np.argmin(a)

3

In [86]:
type(struct)

NameError: name 'struct' is not defined

In [87]:
xrange(10)

xrange(10)

In [88]:
a = xrange(3)

In [89]:
a

xrange(3)

In [1]:
import numpy as np
a = np.array([[0,0,0],[1,1,1],[2,2,2]])

In [3]:
np.mean(a, axis=0)

array([ 1.,  1.,  1.])

In [5]:
np.std(a, axis=0)

array([ 0.81649658,  0.81649658,  0.81649658])